### ISSUE TITLE
Use uniquify

### ISSUE THREAD

**Issue by apconole** [hrs/sensible-defaults.el#1]
Emacs comes with a great package called 'uniquify' (https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html) which will adjust the name of buffers to make them unique when opening the same file.

Example usage:

(require 'uniquify)
(setq uniquify-buffer-name-style 'forward
     uniquify-separator ":")

**Comment by hrs** [comment]
@orgcandman I might not be understanding the benefit of `uniquify`, or maybe I'm just using it wrong.

Suppose I create a couple of files, each named `test`, in two nested directories:

```
.
├── bar
│   └── dir
│       └── test
└── foo
    └── dir
        └── test
```

If I open them side by side in `emacs -Q`, their buffers are named `test<bar>` and `test<foo>`.

Next I run the following code:

``` emacs
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
```

If I reopen the files, their buffers will be named `bar/test` and `foo/test`. The intermediate `dir` is omitted, so it looks like all `uniquify` has done is swap `<...>` for `/`.

The [documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html) implies that I should be seeing `dir` somewhere in those buffer names, right?

(This was on 24.4.1 on a Mac. I'll try it again on a newer build once I get a chance.)

**Comment by apconole** [comment]
Crazy, they must have changed the defaults with 24.X. You can probably close this, then. Looks like there's already a uniquify enabled by default.

**Comment by hrs** [comment]
Cool, that makes sense, and I'll close this. Thanks anyway, though!
