### ISSUE TITLE
Text scale reset

### ISSUE THREAD

**Issue by pajatopmr** [hrs/sensible-defaults.el#2]
Resetting the text scaling is not included as one of the text scale operations.

**Comment by hrs** [comment]
@pajatopmr Sure, I think that'd be useful. It looks like `(text-scale-set 0)` should do the trick.

What key should it be bound to, d'ya think? `C-0` would be the natural choice, but it's already bound. `C-)`, maybe?

**Comment by pajatopmr** [comment]
Yes, C-) is what I use already, so it works for me.

**Comment by hrs** [comment]
Boom, fixed in https://github.com/hrs/sensible-defaults.el/commit/792b58fe9969e92a4f6481281f8febaabeb35d91. Thanks for the suggestion!
