### ISSUE TITLE
Check out better-defaults

### ISSUE THREAD

**Issue by hrs** [hrs/sensible-defaults.el#4]
It looks like [better-defaults](https://github.com/technomancy/better-defaults) provides a lot of the same functionality that we do. We should probably either:
- See if there's enough that differentiates us, and perhaps emphasize it,
- Shut ourselves down, or
- Determine if there are any great ideas in there that we should borrow. :smile:

**Comment by tzz** [comment]
I personally like this codebase better:
- here, the code is modular, not a grab bag of "whatever someone likes"
- here, some defaults can be excluded, which I like a lot
- here, things are thoroughly documented in place, not just in an external README

**Comment by venikx** [comment]
@hrs I just saw your talk about org-mode. Thank you for that!

I've been using Spacemacs and I feel I'm struggling with all the bloat it provides and thought I would start writing my own emacs config from bits and pieces I find from other configs.

I really like how sensible-defaults is not as intrusive as better-defaults. Sensible-defaults does justice to it's name, all the defaults are a nice to have. Better-defaults has too much configuration.

I'm wondering if hiding toolbar, sliders and such should be part of the sensible-defaults or not. Personally I would hide them, but that would mean sensible-defaults would become more opinianated.

Good job on the documentation (especially the docs inside the code, very clear).

**Comment by hrs** [comment]
Thanks, @AnaRobynn! I appreciate it.

> I'm wondering if hiding toolbar, sliders and such should be part of the sensible-defaults or not. Personally I would hide them, but that would mean sensible-defaults would become more opinianated.

I've thought about that! I hide those myself, too, but I'm not sure it's a good default. At least some of the folks using sensible-defaults may be new to Emacs, and while they may eventually want to get rid of some of the chrome, I'm worried that removing all the potentially helpful visual elements will make their experience worse and might scare them off.

Thanks for the suggestion, though! I think I'm gonna close this issue, since it seems like we're all on the same page.
