### ISSUE TITLE
Melpa

### ISSUE THREAD

**Issue by jsborjesson** [hrs/sensible-defaults.el#6]
Hi, great work! Is it possible to release it on melpa? I would love to use it and that would make it simpler than cloning the repo manually. (unless I'm missing something obvious, being quite new to emacs) 

Cheers!

**Comment by benreyn** [comment]
ping @hrs
This is something that I would really like too. Would make it easy to add this to a Cask file and get these auto-magically on a new install. I really don't like using submodules.

**Comment by fearofcode** [comment]
👍

**Comment by hrs** [comment]
I strongly agree! I just submitted a PR to MELPA with a recipe: https://github.com/melpa/melpa/pull/4441.

We'll see how it goes! If it's accepted I'll update the README appropriately and tag a 1.0.0 release for MELPA stable.

**Comment by benreyn** [comment]
Looks like MELPA disagrees with our assessment of this being available as a package there despite better-defaults being available there. 😞

**Comment by hrs** [comment]
Yeah, that's a shame, and I don't really agree with the choice, but I guess I get where they're coming from. MELPA makes my life better consistently enough that I can handle a little disappointment now and then.
