### ISSUE TITLE
sensible-defaults/backup-to-temp-directory is not sensible.

### ISSUE THREAD

**Issue by michaelcadilhac** [hrs/sensible-defaults.el#7]
Howdy hrs;

I do not believe that backing up to the /tmp/ directory is sensible: most Linux distributions nowadays erase /tmp on boot, hence in case of a crash (e.g., empty battery), the backup is lost.

This is naturally debatable, and this is *your* sensibility that should be respected, but this certainly made me lose a good half hour of typing.

Thanks for making your conf public!
M.

**Comment by hrs** [comment]
That's a really good point, @michaelcadilhac, and I'm sorry that happened to you! I think that you're totally right: this isn't a good default.

I've extracted it from the default list in #8, but left it as an optional setting. Does that feel right to you?

**Comment by hrs** [comment]
Fixed in #8.

**Comment by michaelcadilhac** [comment]
That's a perfect solution, thanks for that.  Keep it up!
